---
# Copyright 2023, Technology Innovation Institute

name: Download images from artifactory
description: Download images from artifactory

inputs:
  rt-user:
    description: 'user account for artifactory'
    required: true
  rt-api-key:
     description: 'api-key for artifactory'
     required: true
  rt-url:
    description: 'artifactory url'
    required: true
  input-paths:
    description: 'input-paths in format: { remote_path:remote_path }'
    required: true

runs:
    using: "composite"
    steps:
      - name: Preparing artifactory for download
        uses: "jfrog/setup-jfrog-cli@v3"
      - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
        shell: bash
      - name: Pulling from artifactory
        shell: bash
        env:
          RT_USER: ${{ inputs.rt-user }}
          RT_API_KEY: ${{ inputs.rt-api-key }}
          RT_URL: ${{ inputs.rt-url }}
          INPUT_PATHS: ${{ inputs.input-paths}}
        run: download_artifacts.sh
