name: Publish to artifactory
description: push images to artifactory

inputs:
  rt-user:
    description: 'user account for artifactory'
    required: true
  rt-api-key:
     description: 'api-key for artifactory'
     required: true       
  rt-url:
    description: 'artifactory url'
    required: true  
  bd-num:
    description: build number 
    required: true
  source_dir:
    description: source location of artifacts
    required: true
  dest_dir:
    description: destination location of artifacts
    required: true
  add_bd_num:
    description: append build number to artifact if required
    required: true
    
runs:
    using: "composite"
    steps: 
      - name: Preparing artifactory for upload
        uses: "jfrog/setup-jfrog-cli@v2"
      - name: Pushing to artifactory
        shell: bash
        env: 
          RT_USER: ${{ inputs.rt-user }}
          RT_API_KEY: ${{ inputs.rt-api-key }}
          RT_URL: ${{ inputs.rt-url }}
          BD_NUM: ${{ inputs.bd-num }}
          DIR: ${{ inputs.source_dir }}
          DEST: ${{ inputs.dest_dir }}
          ADD_BD_NUM:  ${{ inputs.add_bd_num }}
        run: |
          jf c add --url "$RT_URL" --user "$RT_USER" --password "$RT_API_KEY"
          jf rt ping
          if "$ADD_BD_NUM" ; then 
          sudo mv $DIR $DIR-b"$BD_NUM"
          jf rt u $DIR-b"$BD_NUM" $DEST --recursive=false
          else
          jf rt u $DIR $DEST --recursive=false
          fi 
