---
# Copyright 2023, Technology Innovation Institute

name: CI development branch verification

on:
  push:
    branches:
      - 'wip/ci/**'
  workflow_dispatch:

jobs:
  build-vm-images:
    uses: ./.github/workflows/build-vm-images.yml
    with:
      branch-override: ${{ github.ref_name }}
    secrets:
      ssh-key: ${{ secrets.CI_SSH_KEY }}
      rt-user: ${{ secrets.RT_USER }}
      rt-api-key: ${{ secrets.RT_APIKEY }}
      rt-url: ${{ secrets.RT_URL }}
