---
# Copyright 2022, Technology Innovation Institute

name: Trigger check for default branch
on:
  push:
    branches:
      - 'tii/development'
  workflow_dispatch:

jobs:
  build-vm-images:
    uses: ./.github/workflows/build-vm-images.yml
    secrets:
      ssh-key: ${{ secrets.CI_SSH_KEY }}
      rt-user: ${{ secrets.RT_USER }}
      rt-api-key: ${{ secrets.RT_APIKEY }}
      rt-url: ${{ secrets.RT_URL }}
