---
# Copyright 2022, Technology Innovation Institute

name: Nightly build
on:
  schedule:
    - cron: '0 3 * * 1-5'

jobs:
  build-vm-images:
    uses: ./.github/workflows/build-vm-images.yml
    secrets:
      ssh-key: ${{ secrets.CI_SSH_KEY }}
      rt-user: ${{ secrets.RT_USER }}
      rt-api-key: ${{ secrets.RT_APIKEY }}
      rt-url: ${{ secrets.RT_URL }}
