---
# Copyright 2023, Technology Innovation Institute

name: Trigger CI development branch verification

on:
  push:
    branches:
      - 'wip/ci/**'
  workflow_dispatch:

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - run: echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"
  build-vm-images:
    needs: pr-check
    uses: ./.github/workflows/build-vm-images.yml
    if: needs.pr-check.outputs.number != 'null'
    with:
      branch-override: ${{ github.ref_name }}
    secrets:
      ssh-key: ${{ secrets.CI_SSH_KEY }}
      rt-user: ${{ secrets.RT_USER }}
      rt-api-key: ${{ secrets.RT_APIKEY }}
      rt-url: ${{ secrets.RT_URL }}

